version: 2
jobs:
  build: 
    working_directory: ~/front-end-test
    docker:
      - image: circleci/node:8.11 
    steps: 
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install Deps
          command: yarn 

       - run:
          name: Run Build
          command: yarn build
          
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  